### ISSUE TITLE
Clarify license and copyright

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dubrousky/javastruct#2]
```
I'm missing information about the license and copyright of the sources. The 
project page says GNU Lesser GPL, but I doubt all files in the subversion trunk 
are covered by this license. Please clarify.

/Mikael
```

Original issue reported on code.google.com by `mikma...@gmail.com` on 11 Jul 2011 at 6:00

**Comment by thelasthappyman** [comment]
Please share license details for this source code. Can we use for production use.

**Comment by dubrousky** [comment]
I suggest consulting the original project https://code.google.com/archive/p/javastruct/ that says it is GPL-licensed.
